dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.16.x
script:
- go mod vendor
- go mod tidy
- make testacc
- make vet
- make build
- make website-test
branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
install:
- bash scripts/gogetcookie.sh
